"""initial migration with user and conversation v2

Revision ID: d5221aa7eb44
Revises: 
Create Date: 2025-02-03 14:35:41.518637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5221aa7eb44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('number', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('user_type', sa.Enum('STUDIO_HEAD', 'PARENT', 'DANCER', 'UNKNOWN', name='usertype'), nullable=True),
    sa.Column('current_state', sa.Enum('START', 'REGISTRATION', 'USER_TYPE_SELECTION', 'STUDIO_HEAD_MENU', 'PARENT_MENU', 'DANCER_MENU', 'COMPETITION_REGISTRATION', 'DANCER_REGISTRATION', 'LICENSE_RENEWAL', 'END', name='conversationstate'), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('state_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
